[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = false
rpc_endpoints ={ sepholia-eth = "https://eth-sepolia.g.alchemy.com/v2/XXXXXX", arbitrun-sepolia ="https://arb-sepolia.g.alchemy.com/v2/XXXXXX" }


remappings = [
    '@openzeppelin=lib/openzeppelin-contracts', 
    '@ccip=lib/ccip',
    '@chainlink/local/=lib/chainlink-local/',
    ]

fs_permissions = [
    {access = "read", path = "./broadcast"},
    {access = "read", path = "./reports"},
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options